### ISSUE TITLE
Seems it doesn't work - No new watchers

### ISSUE THREAD

**Issue by caleb4gr** [ericz99/ebay-watcher#1]
I don't know it seems that it doesn't work. Tried several times with VPN. No luck so far. Any advice?

**Comment by ericz99** [comment]
Yea. you are right. gonna fix it soon.

**Comment by caleb4gr** [comment]
Thanks. You are great.

**Comment by Alexejhero** [comment]
Any updates on when this will be fixed?

**Comment by Alexejhero** [comment]
The watch URL is now a JavaScript button, meaning that you can't just get the href attribute

**Comment by Alexejhero** [comment]
```js
const watchUrl = unescape(JSON.parse(/"addToWatchUrl":(".*?WatchListAddAjax.*?")/g.exec($.html())[1]));
```

This correctly grabs the watch URL from the website.

The endpoint returns 200 OK but no watchers or viewers are added, do you happen to know why?

**Comment by ericz99** [comment]
Hey, I think i know the reason why, and I'm gonna push an update tonight hopefully. I think it's because it's not actually creating the account. Therefore, it can't watch or view the url.

**Comment by ericz99** [comment]
I do have a fix for it, should be available tonight.

**Comment by ericz99** [comment]
This includes the watcher & view repo.

**Comment by caleb4gr** [comment]
I have fixed all the issues. It's working fine. I will post my code later!

**Comment by caleb4gr** [comment]
Here is a demonstration of my version:
Please don't report the comment. I just added it as a proof that it really works. I used a different approach.
https://www.youtube.com/watch?v=RtNYVyAXrhk&feature=youtu.be

**Comment by ericz99** [comment]
No worries, just gotta change few codes around and should be functional again.

**Comment by ericz99** [comment]
Hi, looks like I've fixed the script. If you need help or anything please open another issue. Closing now.
