### ISSUE TITLE
Invalid URI "javascript:;"

### ISSUE THREAD

**Issue by Alexejhero** [ericz99/ebay-watcher#2]
[+] Grabbing watch link...
    [+] RequestError: Error: Invalid URI "javascript:;"

Fix:

```js
const watchUrl = unescape(JSON.parse(/"addToWatchUrl":(".*?WatchListAdd.*?")/g.exec($.html())[1]));
```

This results in:

```
[+] Grabbing watch link...
[+] Successfully watched URL: https://www.ebay.ca/itm/152120842857?var=453630292462&ssPageName=STRK%3AMEBIDX%3AIT&fromMakeTrack=true
```

But still, no watches are added

**Comment by Alexejhero** [comment]
@ericz99 Are you 100% sure this works for you?

**Comment by ericz99** [comment]
Works for US domain, not sure about others. gotta check later.

**Comment by Alexejhero** [comment]
Tested on `.ca` and `.com` and same result on both

**Comment by ericz99** [comment]
Hmm, it works for me for some reason. I’ll check again later. Sorry about that.

**Comment by ericz99** [comment]
You are totally right, and the code provided above got the actual link, but you still won't get any watcher. The whole logic process still works, but it just failed to get the actual watch link. So, I was thinking about converting into a headless version instead of request.

**Comment by ericz99** [comment]
Since, a lot of "people" are abusing this method of increasing watches of their product, my guess is that Ebay already took actions to avoid people abusing their system.

**Comment by Alexejhero** [comment]
Are you sure that the account was even created in the first place?

**Comment by ericz99** [comment]
Yes, the account was created.. I checked each account so there should be no problem..

**Comment by Alexejhero** [comment]
So why are there no watchers added? The script says everything is ok, but `res.body` returns a `It's not you, it's us` error page (server error)

**Comment by ericz99** [comment]
Did you like not read the comment above? The watch url clearly redirects to error page, it still returns a status 200 no matter what, and that is why the script said everything okay. You said if the account was created and it did created, but the main point you’re missing is that it failed to request the watch url because it doesn’t work. And like I said before I’m planning to convert headless instead of request now. Closing this issue for now..

**Comment by Alexejhero** [comment]
I'm not asking any questions, I'm just sharing my thoughts.

---

Over the past few days I have attempted to convert this project to use a headless browser instead of requests, and i have actually made it work in a non-headless environment (I am using puppeteer)

After a few watchers, ebay returned a page which I'm guessing was a ratelimit page:

![](https://cdn.discordapp.com/attachments/615239484136488962/623964210858033163/unknown.png)

After making the environment headless, this page was returned:

![](https://cdn.discordapp.com/attachments/615239484136488962/623968149783707692/unknown.png)

My guess is that my IP was rate-limited and that I should have used proxies.

(Although after setting a proxy in puppeteer, all pages refuse to load with a "No Internet" error)

**Comment by Alexejhero** [comment]
@ericz99 Wait, it works!!
It works perfectly for listings that do not have any "parameters":

For example, it works for this: 

<details>
<summary>Link</summary>

https://www.ebay.com/itm/12-MONTH-XBOX-LIVE-GOLD-MEMBERSHIP-FOR-MICROSOFT-XBOX-360-XBOX-ONE-FAST/333149107000?_trkparms=aid%3D111001%26algo%3DREC.SEED%26ao%3D1%26asc%3D20160908105057%26meid%3D858f1f4557ff4ef6b954cb696d625072%26pid%3D100675%26rk%3D1%26rkt%3D15%26mehot%3Dpp%26sd%3D333149107000%26itm%3D333149107000%26pmt%3D0%26noa%3D1%26pg%3D2481888&_trksid=p2481888.c100675.m4236&_trkparms=pageci%3A5378d73c-dc55-11e9-85a2-74dbd180041a%7Cparentrq%3A533b63f916d0a4e9225e2673ff8ff83c%7Ciid%3A1

</details>

But not for this: 

<details>
<summary>Link</summary>

https://www.ebay.com/itm/1080P-HD-IP66-CCTV-Camera-Waterproof-Outdoor-WiFi-PTZ-Security-Wireless-IR-Cam/233314520444?_trkparms=aid%3D111001%26algo%3DREC.SEED%26ao%3D1%26asc%3D20160908105057%26meid%3Dfecb775cb64642c28ac3ae25fdd93480%26pid%3D100675%26rk%3D4%26rkt%3D15%26mehot%3Dpp%26sd%3D292255196674%26itm%3D233314520444%26pmt%3D1%26noa%3D1%26pg%3D2481888&_trksid=p2481888.c100675.m4236&_trkparms=pageci%3A623773c8-dc56-11e9-bf30-74dbd1801b5c%7Cparentrq%3A5342522b16d0a9e4b8f772a1ff8f24e2%7Ciid%3A1

</details>

This is what I mean by parameters:
![image](https://user-images.githubusercontent.com/32238504/65371761-a5a44e80-dc6f-11e9-883a-b061fd5537a6.png)

The listing with parameters has two additional parameters sent in the request:

```
var: 532832670914
entityInfo: 532832670914^VARIATION
```
